### ISSUE TITLE
Add prometheus /metrics support

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#1]
The idea would be to be able to peek into what's going to give insights into the various measurables, like number of pods matched, filtered and actioned on, the number of machines taken up and down, etc.

**Comment by kz** [comment]
Implemented in PR #58.

**Comment by snehalbiche** [comment]
getting error - 
powerfulseal: error: unrecognized arguments: --prometheus-collector --prometheus-host 192.168.0.1 --prometheus-port 6443

**Comment by kz** [comment]
@snehalbiche PR #58 hasn't been merged yet. Please can you confirm what branch you're on?

**Comment by snehalbiche** [comment]
ohh i thought its merged :( let me know which branch to use?

**Comment by kz** [comment]
@snehalbiche Although I would not recommend it, you should be able to checkout the `feature/metrics` branch under [my account](https://github.com/kz/powerfulseal)'s fork.

I'd recommend waiting a couple days for PR #58 to be merged though!

**Comment by snehalbiche** [comment]
@kz could you please confirm tentative date for this feature to be available? I am looking for this because -

1) Interactive mode does not work with python2.7 and we are using ubuntu 16.4 LTS 
2) I am unable to find logs where I can see powerfulseal in action if I run in Autonomous (policy) mode

 if you could point where I can see powerfulseal logging the information that will help till the feature is merged to master

**Comment by kz** [comment]
@snehalbiche Either later this week or early next week. We have quite a few PRs to review so we'll have to get through the backlog.

As for point 1, please can you let me know what error you're getting when trying to use interactive mode with Python 2.7? Screenshots would be really appreciated.

As for autonomous mode, you can adjust the verbosity of stdout output by using `-v`, `-vv` or `-vvv` flags.

**Comment by kz** [comment]
@snehalbiche FYI - Prometheus metric collection has now been merged into master! If you can, please can you also please send me what error you're getting when using interactive mode with Py2.7? Thanks.

**Comment by snehalbiche** [comment]
@kz Thanks a lot for merging the metric feature, happy to know. Please find screenshots attached. 

![image](https://user-images.githubusercontent.com/19859015/44789067-49c8dc80-abb9-11e8-86a3-63fdc7a3e9eb.png)

**Comment by kz** [comment]
Thanks! I'll look into this.
