### ISSUE TITLE
Version Tracking and Display

### ISSUE THREAD

**Issue by mikeln** [bloomberg/powerfulseal#100]
The cli should have a command to show the current version of powerfulseal.  
This also implies maintaining a semver version value somewhere that corresponds with releases etc.

**Comment by seeker89** [comment]
Good point. We should do that. 👍

**Comment by dgzlopes** [comment]
Hey! Have been researching this one for a while. Following the fifth option here [[0](https://packaging.python.org/guides/single-sourcing-package-version/)] we might use it for taking the version value in setup.py (and keep it as the single source of truth for the version number), and have the project code use the pkg_resources API for reading the version value. As an example:

```python
import pkg_resources

try:
    __version__ = pkg_resources.get_distribution('powerfulseal').version
except Exception:
    __version__ = 'unknown'
```


This is actually how the setuptools [[1](https://github.com/pypa/setuptools)] contributors manage their own version! [[2](https://github.com/pypa/setuptools/blob/master/setuptools/version.py)].

[[0](https://packaging.python.org/guides/single-sourcing-package-version/)] https://packaging.python.org/guides/single-sourcing-package-version/
[[1](https://github.com/pypa/setuptools)] https://github.com/pypa/setuptools
[[2](https://github.com/pypa/setuptools/blob/master/setuptools/version.py)] https://github.com/pypa/setuptools/blob/master/setuptools/version.py

**Comment by seeker89** [comment]
I think that's a pretty neat solution to this problem. Would you like to contribute a PR with that change ?

**Comment by dgzlopes** [comment]
Sure! Working on it right now.

**Comment by mikeln** [comment]
I think we can close this one.
