### ISSUE TITLE
Add Google Cloud (GCP) Cloud Driver

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#123]
Running k8s on top of GCP (with the managed GKE offering or with installer) is pretty common right now, so this might be a great addition. Anyone working on it? If not I would love to start working slowly on this and submit some PR.

**Comment by seeker89** [comment]
As far as I know, the only discussion about Google offerings was in https://github.com/bloomberg/powerfulseal/issues/80

So it's basically yours to take 😄

**Comment by dgzlopes** [comment]
Working on this one slowly! More news shortly. On the other hand, I've been using the k8's side of Powerfulseal whithout problems for the last weeks on the GCP/GKE managed offering (referring #80). I though that maybe adding some docs on how to set it up with gcloud cli may be welcome  (also referring #80). What do you think?

**Comment by fitforgood** [comment]
Hey @dgzlopes - thanks so much for the update !

I'm glad that the driver is coming up, I'm pretty sure there is plenty of people who'd enjoy using that.

Regarding #80 I was really trying to understand what was going wrong there, but the issue died. Did you need to do anything special to work with GCP ?

I think that a quick note in the README about using it would be really good though, if you had 5 minutes to write up how you did that.

Thanks again for your awesome contributions 👍  !

**Comment by seeker89** [comment]
Hey @dgzlopes - thanks so much for the update !

I'm glad that the driver is coming up, I'm pretty sure there is plenty of people who'd enjoy using that.

Regarding #80 I was really trying to understand what was going wrong there, but the issue died. Did you need to do anything special to work with GCP ?

I think that a quick note in the README about using it would be really good though, if you had 5 minutes to write up how you did that.

Thanks again for your awesome contributions 👍 !

**Comment by dgzlopes** [comment]
Nothing too tricky! Bootstrapped GKE, used the common kubectl setup and took the kube-config file. So.. I will review my steps, check if I'm missing something important and write that quick note!

Nope. I should thank you for being an awesome maintainer @seeker89 !  Really smooth experience contributing here.On the other hand, it's really fun to make the Seal more powerful.

**Comment by seeker89** [comment]
Double awesome 👍 🎉
