### ISSUE TITLE
Web UI Should Show Actions Performed By Default

### ISSUE THREAD

**Issue by mikeln** [bloomberg/powerfulseal#125]
When running in Autonomous mode with a policy-file, the Web UI does not show the actions performed against the target system in the Logs screen by default.  

With no logging enabled, it is very hard to monitor what actions are being performed against the target system.

Suggest either 1) adding consistent "info" logs to each action, or 2) adding a new message level (of some sort) to enable web UI action monitoring.

**Comment by monolithh** [comment]
It would be nice to have this behaviour by default. However, if you want to see logs in UI like in a console output just add `-vv`. I have added `-vv` before `autonomous` and this is works for me

**Comment by seeker89** [comment]
This should have been fixed by https://github.com/bloomberg/powerfulseal/pull/219. Feel free to reopen if it's still the case.
