### ISSUE TITLE
Seal crashed trying to kill a pod in pending state.

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#127]
**Describe the bug**
Seal crashes if I try to kill a pod in pending state while running on Interactive mode.

**To Reproduce**
1. Run Seal
2. List pods with ```pods```
3. Kill one pod ```kill <number>```

**Expected behavior**
Warning/Error message should be displayed while handling the exception. Might be interesting to add to pods state some color scheme, as we have on nodes state.

**Comment by seeker89** [comment]
Good catch. 👍
