### ISSUE TITLE
Enhancement: add Datadog /metrics support

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#132]
> Datadog [[0](https://www.datadoghq.com/)] is a monitoring service for cloud-scale applications, providing monitoring of servers, databases, tools, and services, through a SaaS-based data analytics platform.

The idea is to add a Datadog metrics collector to have insights into the various measurables of Powerfulseal (similar to the Prometheus one). Adding a new metrics collector seems straightforward! So if this feature looks reasonable for the project, I would like to work on it and submit a PR when ready.

[0] https://www.datadoghq.com/

**Comment by seeker89** [comment]
I don't see why not. It should indeed be straightforward to add it - go for it 👍
