### ISSUE TITLE
Azure driver DeprecationWarning

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#135]
This warning is visible in the CI logs:

```
.tox/py27/lib/python2.7/site-packages/azure/mgmt/compute/models.py:15
  /Users/mpawlikowsk1/github/powerfuseal/.tox/py27/lib/python2.7/site-packages/azure/mgmt/compute/models.py:15: DeprecationWarning: Import models from this file is deprecated. See https://aka.ms/pysdkmodels
    DeprecationWarning)
```

We should fix it, as described in the message.

**Comment by seeker89** [comment]
@mikeln Have you got an idea of what needs to be done to make azure happy again ? Many thanks !

**Comment by mikeln** [comment]
looking, but this is the initial stuff from Azure: https://github.com/Azure/azure-sdk-for-python/wiki/Direct-access-to-%22models%22-is-deprecated

**Comment by mikeln** [comment]
I think I accidentally left in an unneeded import.  Checking now.

**Comment by mikeln** [comment]
This should fix it.
https://github.com/bloomberg/powerfulseal/pull/141
