### ISSUE TITLE
Allow powerfulseal UI to work correctly behind a proxy 

### ISSUE THREAD

**Issue by monolithh** [bloomberg/powerfulseal#178]
First of all, I would say thank you for the great chaos tool

**Is your feature request related to a problem? Please describe.**
I have faced an issue related to UI, especially to Flask. I have a load balancer which only listens 443 port (80 port is closed). When I open powerfulseal UI it is work in general but it shows in `Autonomous Mode` `Status: Error`. This happens because of Flask doesn't "read" HTTP headers like X-Forwarded- and populate inside UI links with HTTP schema. Chrome shows errors in console "Mixed content" and you can just skip it and load "unsafe" parts over HTTP ... But only if you have opened 80 HTTP port. In my case UI goes broken (as I said earlier I have closed 80 port). 

**Describe the solution you'd like**
The fix is here: https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/
This will allow powerfulseal to "read" HTTP headers like X-Forwarded-

**Additional context**
Tested on docker image: powerfulseal:2.7.0

**Comment by seeker89** [comment]
Hi @monolithh - thanks for raising this! The solution you are suggesting sounds reasonable. Would you have any bandwidth to PR by any chance? :)

**Comment by monolithh** [comment]
@seeker89 PR is ready to merge

**Comment by seeker89** [comment]
Resolved via #182
