### ISSUE TITLE
kubernetes deployment don't work

### ISSUE THREAD

**Issue by mhamdisemah** [bloomberg/powerfulseal#186]
**Describe the bug**
the dockerhub image url isn't correct for the powerfulseal kubernetes deployment description .
[https://github.com/bloomberg/powerfulseal/blob/master/kubernetes/powerfulseal.yml](url)

**Environment:**
 - cloud provider: GKE
**Solution:**
change the url of the powerfulseal image in dockerhub

**Comment by seeker89** [comment]
Resolved via #187
