### ISSUE TITLE
Unrecognized arguments: --use-pod-delete-instead-of-ssh-kill

### ISSUE THREAD

**Issue by ArseniiPetrovich** [bloomberg/powerfulseal#192]
**Describe the bug**
I've tried to run the very basic installation of powerfulseal - through the Kubectl deployment manifest, but my powerfulseal pod ran into crash loop. The error log:
```
ubuntu@selfportal:~$ kubectl logs powerfulseal-7bd4dddc5d-9fjzb
usage: powerfulseal [-h] [-c CONFIG] [-v] [-V]
                    {interactive,autonomous,label,demo,validate} ...
powerfulseal: error: unrecognized arguments: --use-pod-delete-instead-of-ssh-kill
```
When you manually delete the `--use-pod-delete-instead-of-ssh-kill` argument it start working again, but it seems that this argument is essential for in-container installation, so any help would be much appreciated here.

**To Reproduce**
1. Clone this repo.
2. Open this repo
3. Go to the `kubernetes` folder`
4. kubectl apply -f .
5. `kubectl get po` and `kubectl logs` to check the error.

**Expected behavior**
Powerful seal starts without errors.

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04] Ubuntu Linux 18.04
 - Browser [e.g. Firefox, Safari] (if applicable): n/a

**Comment by seeker89** [comment]
Hi, thanks for finding this. IIRC (AFK) it should be version 2.6.0 - could you change the image version in the yaml and try again? And if it works, a PR fixing the yaml would be the most welcome! :)

**Comment by ArseniiPetrovich** [comment]
Hi, @seeker89, thanks for your answer! It definitely works with 2.6.0!
Updated the default configuration and prepared a PR for you ;)

**Comment by seeker89** [comment]
Thanks ! 👍
