### ISSUE TITLE
UI doesn't respect --use-pod-delete-instead-of-ssh-kill flag

### ISSUE THREAD

**Issue by abhinandan1989** [bloomberg/powerfulseal#195]
Hello,
I try do do setup for test my k8s nodes and pods but I am failing to do it for multiple clusters
  and when i am tying to create or apply powerfulseal.yml file its not recognize the powerfulseal, 
Guys can you please help me to do setup for test my k8s. 

I have requirement like this, I want to kill random pods and nods from specific namespace and monitor the performance of my services.

I am using centOS,
Thank you

**Comment by seeker89** [comment]
You're going to need to give us a bit more context on what is it that you're failing to do specifically, and how you're setting up your powerfulseal.

I would recommend to start with something along the lines of

```sh
seal \
  -vv \
  interactive \
    --no-cloud \
    --inventory-kubernetes \
    --ssh-allow-missing-host-keys
```

to first debug the kubernetes part, and then once that's working, debug the rest.

**Comment by abhinandan1989** [comment]
Hi Mikolaj Pawlikowski,

I did the setup of powerfulseal 

I have 3 nodes like master, node1, node2

root@master:/home/osboxes/testing# ls
nginx.yaml  powerfulseal.yml  rbac.yml

root@master:/home/osboxes/testing# kubectl get nodes -n default
NAME     STATUS   ROLES    AGE    VERSION
master   Ready    master   2d4h   v1.16.3
node1    Ready    <none>   2d3h   v1.16.3
node2    Ready    <none>   2d3h   v1.16.3

I created 5 replica of nginx in default namespace(master)

root@master:/home/osboxes/testing# kubectl get pod -n default
NAME                            READY   STATUS    RESTARTS   AGE
my-nginx-75897978cd-269js       1/1     Running   0          147m
my-nginx-75897978cd-28p4w       1/1     Running   0          147m
my-nginx-75897978cd-98fnn       1/1     Running   0          147m
my-nginx-75897978cd-r4zzd       1/1     Running   0          147m
my-nginx-75897978cd-sxcgv       1/1     Running   0          147m
powerfulseal-588cdb7b68-qd8b4   1/1     Running   15         144m
root@master:/home/osboxes/testing# 


I started powerfulseal and I listout the namespaces and try to kill pods but i am getting error. you can see billow

sboxes@master:~$ sudo su
[sudo] password for osboxes: 
root@master:/home/osboxes# seal \
>   -vv \
>   interactive \
>     --no-cloud \
>     --inventory-kubernetes \
>     --ssh-allow-missing-host-keys
2019-12-04 06:47:15 master powerfulseal[10294] INFO modules powerfulseal.cli.__main__ : verbosity 2 : log level DEBUG : handler level INFO 
2019-12-04 06:47:15 master powerfulseal.cli.__main__[10294] INFO Creating kubernetes client with config /root/.kube/config (path found for backwards compatibility)
2019-12-04 06:47:15 master powerfulseal.k8s.k8s_client[10294] INFO Initializing with config: /root/.kube/config
2019-12-04 06:47:15 master powerfulseal[10294] INFO No driver - some functionality disabled
2019-12-04 06:47:15 master powerfulseal[10294] INFO Attempting to read the inventory from kubernetes
2019-12-04 06:47:15 master powerfulseal.node.node_inventory[10294] INFO Sync Nodes
2019-12-04 06:47:15 master powerfulseal.clouddrivers.no_cloud_driver[10294] ERROR Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2019-12-04 06:47:15 master powerfulseal[10294] INFO STARTING INTERACTIVE MODE
(seal) $ namespaces
2019-12-04 06:47:28 master powerfulseal.k8s.k8s_inventory[10294] INFO Reading kubernetes namespaces
default
kube-node-lease
kube-public
kube-system
(seal) $ pods default
[pod #0 name=my-nginx-75897978cd-269js namespace=default containers=1 ip=192.168.104.39 host_ip=10.13.177.202 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #1 name=my-nginx-75897978cd-28p4w namespace=default containers=1 ip=192.168.104.40 host_ip=10.13.177.202 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #2 name=my-nginx-75897978cd-98fnn namespace=default containers=1 ip=192.168.166.165 host_ip=10.13.176.64 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #3 name=my-nginx-75897978cd-r4zzd namespace=default containers=1 ip=192.168.104.41 host_ip=10.13.177.202 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #4 name=my-nginx-75897978cd-sxcgv namespace=default containers=1 ip=192.168.166.164 host_ip=10.13.176.64 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #5 name=powerfulseal-588cdb7b68-qd8b4 namespace=default containers=1 ip=192.168.104.42 host_ip=10.13.177.202 state=Running labels:pod-template-hash=588cdb7b68,name=powerfulseal]
(seal) $ kill 1
Will execute 'sudo docker kill -s SIGKILL f66f8751720a82bb306744ece09aa1e59d5022b9a0111e072e0d3ca155fcb763' on [node no=18 id=fake-10.13.177.202 ip=10.13.177.202 extIp=10.13.177.202 az=nope groups=['amd64', 'linux', 'node2'] name=local-10.13.177.202 state=NodeState.UNKNOWN]. Continue ? [y/n]: 
y
2019-12-04 06:47:54 master powerfulseal.execute.remote_executor[10294] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL f66f8751720a82bb306744ece09aa1e59d5022b9a0111e072e0d3ca155fcb763']' on local-10.13.177.202
No handlers could be found for logger "paramiko.transport"
2019-12-04 06:47:54 master powerfulseal.execute.remote_executor[10294] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL f66f8751720a82bb306744ece09aa1e59d5022b9a0111e072e0d3ca155fcb763']' on local-10.13.177.202 failed with error: Raw
--------------------------------------------------------------------------------
10.13.177.202


Raw
(seal) $ 

Can you please help me to resolve this issue (How can i kill the pods on cluster level)

**Comment by seeker89** [comment]
Hi, thanks for the extra info.

The error you're seeing is because by default, powerfulseal tries to kill pods through issuing `docker kill` command via `ssh` into the node. It's to ensure the most realistic way of killing - it will show up as a crash in `kubernetes`. It looks like your ssh is not setup correctly.

An alternative to using `ssh` is to add `--use-pod-delete-instead-of-ssh-kill` option when you're starting your `seal`. This way it will use `kubernetes` API to delete the pods, rather than crashing them. I suggest you give it a go.

**Comment by abhinandan1989** [comment]
Hi,
Still I am getting same log.

steps i followed for creating my clusters and installing powerfulseal 

Step 1 >> created 3 VM with Ubuntu OS
Step 2 >> install Docker in all env
Step 3 >> did setup for kubeadm
Step 4 >> install  kubectl in all 3 nodes 
Step 5 >> install powerfulseal in master node >>  https://github.com/bloomberg/powerfulseal#setup
No changes in rbac and powerfulseal yml i kept same as your file

But, I am thinking issue in billow commands which i am passing to start the seal : can you please help me to how to resolve this issue for cluster  
seal \
  -vv \
  interactive \
    --no-cloud \
    --inventory-kubernetes \
    --ssh-allow-missing-host-keys \
    --remote-user root \
how to get this billow details in my case because of I am not using minikube 
    **--ssh-path-to-private-key `minikube ssh-key` \
    --ssh-password `minikube ssh-password` \
    --override-ssh-host `minikube ip`**


root@master:/home/osboxes# seal -vv interactive --no-cloud --inventory-kubernetes --ssh-allow-missing-host-keys --use-pod-delete-instead-of-ssh-kill
2019-12-05 01:05:46 master powerfulseal[4875] INFO modules powerfulseal.cli.__main__ : verbosity 2 : log level DEBUG : handler level INFO 
2019-12-05 01:05:46 master powerfulseal.cli.__main__[4875] INFO Creating kubernetes client with config /root/.kube/config (path found for backwards compatibility)
2019-12-05 01:05:46 master powerfulseal.k8s.k8s_client[4875] INFO Initializing with config: /root/.kube/config
2019-12-05 01:05:46 master powerfulseal[4875] INFO No driver - some functionality disabled
2019-12-05 01:05:46 master powerfulseal[4875] INFO Attempting to read the inventory from kubernetes
2019-12-05 01:05:46 master powerfulseal.node.node_inventory[4875] INFO Sync Nodes
2019-12-05 01:05:46 master powerfulseal.clouddrivers.no_cloud_driver[4875] ERROR Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2019-12-05 01:05:46 master powerfulseal[4875] INFO STARTING INTERACTIVE MODE
(seal) $ pods default
[pod #0 name=my-nginx-75897978cd-874rv namespace=default containers=1 ip=192.168.166.169 host_ip=10.13.176.64 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #1 name=my-nginx-75897978cd-89bxk namespace=default containers=1 ip=192.168.166.170 host_ip=10.13.176.64 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #2 name=my-nginx-75897978cd-9k2wx namespace=default containers=1 ip=192.168.104.47 host_ip=10.13.177.202 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #3 name=my-nginx-75897978cd-mgdkq namespace=default containers=1 ip=192.168.166.168 host_ip=10.13.176.64 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #4 name=my-nginx-75897978cd-zrk9t namespace=default containers=1 ip=192.168.104.48 host_ip=10.13.177.202 state=Running labels:pod-template-hash=75897978cd,run=my-nginx]
[pod #5 name=powerfulseal-588cdb7b68-jl76w namespace=default containers=1 ip=192.168.104.49 host_ip=10.13.177.202 state=Running labels:pod-template-hash=588cdb7b68,name=powerfulseal]
(seal) $ kill 2
Will execute 'sudo docker kill -s SIGKILL 97a3a81c559a7f4edb7ecf84847bd9dfb3cc598fb5d04015a30ff146630c5973' on [node no=18 id=fake-10.13.177.202 ip=10.13.177.202 extIp=10.13.177.202 az=nope groups=['amd64', 'linux', 'node2'] name=local-10.13.177.202 state=NodeState.UNKNOWN]. Continue ? [y/n]: 
y
2019-12-05 01:06:20 master powerfulseal.execute.remote_executor[4875] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 97a3a81c559a7f4edb7ecf84847bd9dfb3cc598fb5d04015a30ff146630c5973']' on local-10.13.177.202
2019-12-05 01:06:21 master powerfulseal.execute.remote_executor[4875] INFO Executing '['sh', '-c', 'sudo docker kill -s SIGKILL 97a3a81c559a7f4edb7ecf84847bd9dfb3cc598fb5d04015a30ff146630c5973']' on local-10.13.177.202 failed with error: Error creating SSH connection
Original error: No authentication methods available
--------------------------------------------------------------------------------
10.13.177.202


Error creating SSH connection
Original error: No authentication methods available
(seal) $

**Comment by seeker89** [comment]
Which version of the seal are you running?

I can see that despite passing on the `--ssh-allow-missing-host-keys ` option, your seal is still trying to use ssh - there was a bug causing this in versions before `2.8.0`.

**Comment by jeblackmore** [comment]
Hi. I've just started using the 2.8.0 Docker image and am experiencing the same problem, i.e. the seal is using docker kill (and failing due to SSH) even when I specify `--ssh-allow-missing-host-keys` and `--use-pod-delete-instead-of-ssh-kill`. I'm running in autonomous mode (with a minimal policy file) and using the Kill button on the UI.

**Comment by jeblackmore** [comment]
Keeping the seal configuration the same, I tried adding a podScenario with a label selector and force kill and that works. Looks like its using the K8S API, as if I remove the `--use-pod-delete-instead-of-ssh-kill` arg it fails with the SSH error. Using the UI Kill button still fails either way, so that suggests its trying to use the docker kill regardless of the `--use-pod-delete-instead-of-ssh-kill` when called from the UI.

**Comment by seeker89** [comment]
You're right - I just checked the code, and I can see that the UI button didn't get support for the `--use-pod-delete-instead-of-ssh-kill` flag. Thanks for catching that!

I am hoping to do an overhaul of the UI in the near future, so I'll try to address that. I'll mark as a bug.

**Comment by seeker89** [comment]
This is now a mute point after https://github.com/bloomberg/powerfulseal/pull/219/

**Comment by nirutgupta** [comment]
Its not yet resolved @seeker89. I was trying to do the same but still facing the issue.

**Comment by seeker89** [comment]
Hi @nirutgupta which version were you running?

The versions 3.0.0rc no longer have the kill option from the UI, so this is a moot point.

**Comment by nirutgupta** [comment]
Oh okay i was using 2.9.0. Also is there an option to delete deployments as well ?

**Comment by seeker89** [comment]
You can use the `kubectl` action https://bloomberg.github.io/powerfulseal/schema/#scenarios_array_items__steps_array_items__option2__kubectl__action
