### ISSUE TITLE
Push to PyPi

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#2]
For an even quicker way of starting, it would be great to have a quick `docker run` command.

**Comment by kpfleming** [comment]
Not quite sure about that... 'pip install' is pretty quick already. Building a container image means maintaining it (updating it for security fixes, etc.), so it's a non-trivial thing to do.

**Comment by kpfleming** [comment]
What *would* be good is to ship this to PyPi, if it's suitable for that.

**Comment by seeker89** [comment]
That's fair. Let's start with PyPi and take it from there.
