### ISSUE TITLE
Check the status of the injected failures/targeted components

### ISSUE THREAD

**Issue by chaitanyaenr** [bloomberg/powerfulseal#203]
**Is your feature request related to a problem? Please describe.**
We ran powerfulseal on an OpenShift cluster and it works perfectly as expected. There were couple of features missing and we were wondering if they can be considered as the potential enhancements: 
1) The tool doesn't report the status of the chaos experiment/failure injection after completing the iterations/loopsNumber specified in the config when running it from inside the cluster.  

2) Is there a supported option to check/run action at the end of the chaos scenario to verify if the cluster/component recovered from the failure. We do understand that the tool is generic in the sense that it targets random pods instead of specific components but this feature will be useful where powerfulseal config is tailored for a particular component like kube-apiserver, etcd e.t.c For the random kill, the number of pod ( running state ) count before kill and after recovery can be checked for example. This would be very useful when automating the experiments to run them on a schedule with no human checking the state of the cluster. 

**Describe the solution you'd like**
1) The pod status should reflect whether it succeeded/completed or failed to inject the specified set of scenarios if it's set to run for a limited number of iterations/loops instead of the pod status being in "Running" state. This way, we can use the pod status to determine pass/fail. 

2) Add support to mention an action in the config which accepts a command or a script containing the logic to check if the cluster/component recovered after a failure has been injected. This way the tool not kills a component/injects a failure but also checks if the cluster recovered as expected and if it doesn't, we can improve the component to be more resilient.

**Describe alternatives you've considered**
Each user can write a wrapper around the chaos scenario to do the check mentioned in the second solution above.

We would love to hear your thoughts or feedback. Thanks.

**Comment by chaitanyaenr** [comment]
cc: @seeker89, @dgzlopes

**Comment by dgzlopes** [comment]
Thank you for taking the time to write these feature requests :)

Even if I don't run Powerfulseal inside K8s, I think that both proposals are very interesting.

Using the pod status phase (succeeded/failed) to reflect the scenario outcome seems useful. In fact, it would allow users to automatically re-deploy Powerfulseal with different scenarios/configs in case some of them fail.

Regarding the second one, I can see the benefit of having a 'local-execute' action or adding some kind of flag (local: true) to the existing execute action [1]. Something like Terraform [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html), that invokes a process on the machine running Terraform.

[1] Right now it's used only by [NodeScenarios](https://github.com/bloomberg/powerfulseal/blob/9030721cb0f14d802cf1afa3817837c9367516a6/tests/policy/example_config.yml#L90)

**Comment by chaitanyaenr** [comment]
@dgzlopes thanks for the feedback. Are the features something that can be considered to be added in the near future? We are more than happy to collaborate.

**Comment by dgzlopes** [comment]
I would love to hear what @seeker89  thinks about the features :)

**Comment by seeker89** [comment]
Hi @chaitanyaenr and sorry for taking some time to get to this - the pandemic situation is crazy right now...

I like both ideas 👍 

I would start by adding the second one. I think that we could cover a large chunk of validation with just two options:
- an http call (with configurable timeout and wait time before calling, max number of retris, the expected status code and perhaps a quick validation of the body, in case you need to work with a badly designed API)
- a custom command executed over the SSH (if running in this mode)

This would allow for plugging in validation that works for a lot of cases out of the box.
In terms of implementation, I would see it as a new stage: after matching, filtering and acting, it's time to validate.


Then, once the validation is in place, let's address the first one and make sure we return a meaningful response code. To go further, we could even add an optional HTTP webhook, which the seal could call with the results of the experiment once it's finished.

What do you think? Does it sound like a plan? @chaitanyaenr @dgzlopes

**Comment by dgzlopes** [comment]
LGTM! 

Maybe we can pick some ideas from [K8s container probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes). It looks quite similar to what we are trying to accomplish here and K8s users already know the syntax.

Right now it has command, HTTP and TPC probes. Some examples [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).

**Comment by chaitanyaenr** [comment]
@seeker89 @dgzlopes sounds like a plan. Thanks for the pointers.

**Comment by seeker89** [comment]
FYI, I'll be getting to this soon: https://github.com/bloomberg/powerfulseal/issues/224 

So if you've got stuff to push, it would be easeri to do it now to avoid clashes :)

**Comment by chaitanyaenr** [comment]
@seeker89 We haven't started the implementation yet, feel free to start on the implementation. Thanks for checking and looking forward to the new feature.
