### ISSUE TITLE
Speed up TravisCI builds

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#208]
Right now builds take around ~8min to complete (total time). I found that we spend ~1.50min per job building the docker container, even when we don't use it.

I think it might be a good idea to build the container only on new releases.

**Comment by seeker89** [comment]
This is by design - to make sure that it behaves the same way in Dockerfile on any change.

**Comment by dgzlopes** [comment]
Oh! Makes sense :) 

Closing this one.
