### ISSUE TITLE
Running with `--inventory-kubernetes` fails to find host in known_hosts

### ISSUE THREAD

**Issue by skamboj** [bloomberg/powerfulseal#21]
## Summary

In interactive mode, for certain commands, the powerful seal tries to ssh into a destination host to run the command. Using the `--inventory-kubernetes` flag makes the seal try to guess the inventory from kubernetes but if a host has both a public IP address and a private IP address, it tends to find the public IP address and then have ssh complain about the IP address not being present in known_hosts. 

## Steps to reproduce

1. Run powerfulseal with `powerfulseal --inventory-kubernetes --interactive --kube-config /kubernetes/conf/kubeconfig`
2. Give the command `docker`. We get an error of the form:

```
Executing '['sh', '-c', 'sudo docker ']' on sk1-worker-1
--------------------------------------------------------------------------------
xxx.xxx.xxx.xxx


Error creating SSH connection
Original error: Server 'xxx.xxx.xxx.xxx' not found in known_hosts
```

Where `xxx.xxx.xxx.xxx` is the public IP address of a host that is present in known hosts.

**Comment by seeker89** [comment]
This was fixed via introduction of the `--ssh-allow-missing-host-keys` flag.
