### ISSUE TITLE
use-pod-delete-instead-of-ssh-kill argument is ignored in label mode 

### ISSUE THREAD

**Issue by jpenekusu** [bloomberg/powerfulseal#210]
**Describe the bug**
I run powerfulseal in label mode with use-pod-delete-instead-of-ssh-kill parameter enabled.
But powerfulseal still tries to kill pods using ssh (sudo docker kill -s SIGKILL ...etc) instead of simple API calls.
I cannot use ssh killing mode in my OpenShift platform since this protocol is not allowed. 

**To Reproduce**

I created a powerfulseal image using git version 1ac2623feaaed264bbea4924eb31ffbff49f5910

1. Run a pod chaos scenario with powerfulseal using following parameters. I use run powerfulseal in OpenShift with a deploymentConfig, passing these arguments:
          args:
          - label
          - --no-cloud
          - --**use-pod-delete-instead-of-ssh-kill**
          - --min-seconds-between-runs 20
          - --max-seconds-between-runs 60
          - --inventory-kubernetes 
          - --kubernetes-namespace=mynamespace
          - --prometheus-collector
          - --prometheus-host 0.0.0.0
          - --prometheus-port 8081

I set following labels on pods that I want powerfulseal to kill:
    seal/enabled: 'true'
    seal/end-time: 23-59-00
    seal/force-kill: 'true'
    seal/kill-probability: '1.0'
    seal/start-time: 00-01-00
Here are pod error logs:

2020-04-21 17:43:27 powerfulseal-lb-1-jkfch powerfulseal.clouddrivers.no_cloud_driver[1] INFO Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
2020-04-21 17:43:27 powerfulseal-lb-1-jkfch powerfulseal.policy.label_runner[1] INFO Found 3 pods
2020-04-21 17:43:27 powerfulseal-lb-1-jkfch powerfulseal.policy.label_runner[1] INFO Filtered to 2 pods
2020-04-21 17:43:27 powerfulseal-lb-1-jkfch powerfulseal.policy.label_runner[1] INFO Action execute 'sudo docker kill -s SIGKILL badb8e2fca2da66ecfcb8dc833793d379650ac4ebf5038478ea86d1ed08a4d60' on [pod #0 name=mypod-15-2ltp6 namespace=mynamespace containers=1 ip=w.x.y.z host_ip=z.y.x.w state=Running labels:app=mypod,deployment=mydeployment-15,deploymentconfig=mydeployment,seal/enabled=true,seal/end-time=23-59-00,seal/force-kill=true,seal/kill-probability=1.0,seal/start-time=00-01-00]
2020-04-21 17:43:27 powerfulseal-lb-1-jkfch powerfulseal.execute.remote_executor[1] INFO Executing '['sh', '-c', '**sudo docker kill -s SIGKILL badb8e2fca2da66ecfcb8dc833793d379650ac4ebf5038478ea86d1ed08a4d60**']' on local-z.y.w.v

**Expected behavior**
When the argument use-pod-delete-instead-of-ssh-kill is activated, powerfulseal should kill pods using k8s API instead of ssh.

**Environment (please complete the following information):**
 - Operating System and Version: OpenShift 3.9 on RedHat 7
 
**Additional context**
The agument use-pod-delete-instead-of-ssh-kill works as expected in autonomous mode.
But I want to use label mode to let namespace owner configure chaos policy rules (in opposite to autonomous mode where policy rules are centraly managed by powerfulseal in configmap).

**Comment by seeker89** [comment]
You're right. The `LabelRunner` missed the update on the `--use-pod-delete-instead-of-ssh-kill` flag. This:

https://github.com/bloomberg/powerfulseal/blob/bea1e499b4957d88ddc5b0bd3d308a77a74629b3/powerfulseal/policy/label_runner.py#L73-L77

Should include a similar clause as this:

https://github.com/bloomberg/powerfulseal/blob/bea1e499b4957d88ddc5b0bd3d308a77a74629b3/powerfulseal/policy/pod_scenario.py#L98-L111

It should be a quick fix, I'll mark it as good first issue.

Thanks for raising this!

**Comment by jpenekusu** [comment]
I made a couple of changes on the code snippet provided above. It work like a charm now (i.e: the argument --use-pod-delete-instead-of-ssh-kill is now taken into account in labelRunner and and autonomousRunner).
Could I raise a PR with this fixing ?
Thanks you.

Here is the added code:

        # In case we are setup to delete pods, instead of SSHing
        if self.k8s_inventory.delete_pods:
            self.logger.info("Deleting pod %r", pod)
            try:
                self.k8s_inventory.k8s_client.delete_pods([pod])
                self.metric_collector.add_pod_killed_metric(pod)
            except:
                self.metric_collector.add_pod_kill_failed_metric(pod)
            return

**Comment by seeker89** [comment]
Absolutely! Looking forward to a PR. 

Please just remember to commit your changes [including the signoff](https://github.com/bloomberg/powerfulseal/blob/master/CONTRIBUTING.md#contribution-licensing), for example through adding the `-s` to your `git commit` line.

Thanks!

**Comment by jpenekusu** [comment]
@seeker89 ,
I added a unit test and updated the two current ones.
Could you have a look and merge the PR to master if OK ?
