### ISSUE TITLE
Allow more than one namespace in labelRunner mode

### ISSUE THREAD

**Issue by jpenekusu** [bloomberg/powerfulseal#214]
**Is your feature request related to a problem? Please describe.**
In labelRunner mode, powerfulseal uses pod labels combined to the argument --kubernetes-namespace to discover pods eligible to chaos engineering.
But there is a limitation on the argument --kubernetes-namespace that can only take two values: 
- a single namespace (eg: --kubernetes-namespace=my-namespace) to run the chaos only into that namespace
- a space (eg: --kubernetes-namespace=) to run the chaos on all eligible pods of the entire cluster (all namespaces are scanned by powerfulseal service discovery)

**Describe the solution you'd like**
Like in autonomousRunner mode, I want to be able to provide a set of namespaces on which to execute the chaos engineering.
The courrent solution is binary: I can only provide one or all namespaces to powerfulseal. It should be possible to provide a list of namespaces to powerfulseal like in autonomous mode, even with a solution less rich than in autonomous mode.

**Describe alternatives you've considered**
The only alternative is to set the argument --kubernetes-namespace to space (i.e: --kubernetes-namespace=) to get all pods across all namespaces, which is not recommended due to poor performance !

**Additional context**
I will provide chaos engineering services to many team (i.e: namespaces) and I want to limit the pod service descovery to that set of namespaces in place of the entire cluster.
One more thing, if the argument --kubernetes-namespace equals space (i.e: --kubernetes-namespace=), powerfulseal serviceaccount will require to be granted the clusterRole "list/get" pods. This is very limiting since it requires to have admin rights on the k8s cluster to create and grant a clusterRole.

**Comment by seeker89** [comment]
This is a good point, and I think that a simple comma-separated list of namespaces would be a very welcome addition.

In fact, we could add support to everywhere by tweaking https://github.com/bloomberg/powerfulseal/blob/c388736f90bc27fc75a8a5de1131253659bb5063/powerfulseal/k8s/k8s_inventory.py#L89-L94 to iterate over namespaces, that https://github.com/bloomberg/powerfulseal/blob/c388736f90bc27fc75a8a5de1131253659bb5063/powerfulseal/k8s/k8s_inventory.py#L51-L58 could return always as a list
