### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#228]
I think our Readme is too big and a bit scary for newcomers. Any thoughts on moving the docs to ReadTheDocs or Github Pages? [0]

I'm happy to contribute/move/refactor the docs to the new platform :)

[0] Nothing fancy. Maybe Sphinx or MkDocs using plain Markdown? [Alabaster](https://alabaster.readthedocs.io/en/latest/) theme looks awesome, and it's available for both of them.

**Comment by seeker89** [comment]
I think that a plain Markdown github pages would be awesome.

I have the same feeling - the README is a little bit large and some people get lost.
I was thinking that it would be awesome to write some kind of tutorial, which leads a new user from zero to some basic policies. That would really help I think.

**Comment by jcstanaway** [comment]
I found that the docs were incomplete when it came to writing policies.  I ended having to dig into the code to understand how some of the various filter options actually worked.  And then created additional documentation for our teams to reference when creating their own scenarios.  I'm willing to provide more detailed feedback.

**Comment by dgzlopes** [comment]
Yep! Some kind of quickstart would be awesome @seeker89

I agree 100% @jcstanaway. We need more detailed docs regarding Autonomous mode and Policy creation.

Some more ideas:
-  Replace Interactive mode gifs with Asciinema recordings (Easier to stop/read).
-  Explain when/why you should use Interactive/Autonomous/Label mode.
-  Add some "real-world" Policy examples.

I'm working on moving the docs to plain Markdown Github pages as @seeker89 proposed. Might have something ready later today :)

**Comment by seeker89** [comment]
Fantastic!

@jcstanaway would you be open to providing some sanitised example policies to the docs?

**Comment by seeker89** [comment]
I started working on auto-generating docs from the schema for easier browsing: https://github.com/bloomberg/powerfulseal/pull/235

We should integrate that into the Github page documentation. For now I've put them in `/docs-schema` subfolder.

**Comment by jcstanaway** [comment]
Sure, I'll put some together shortly.

I was also going to propose updating the schema to provide more specifics and incorporate constraints implemented in the code.  As it is, I can write a policy that passes the validation checks, but will fail during execution.  As I expect to have multiple contributors to our policy definitions, I have a CI job that uses the validation command and would like for the schema to be more rigorous.

**Comment by dgzlopes** [comment]
Closing in favor of #240

**Comment by seeker89** [comment]
@jcstanaway 

Created https://github.com/bloomberg/powerfulseal/issues/241 to track the schema improvements.
