### ISSUE TITLE
Commands that take a subset of hosts return silently when the subset name is unknown

### ISSUE THREAD

**Issue by skamboj** [bloomberg/powerfulseal#23]
Commands that take a subset of hosts return silently when the subset name does not match any known string. For example, running `docker thisdoesnotexist` will return silently. This should be an explicit error if the string is not known as users are likely to accidentally forget the string and type something like `docker info` and then wonder why it returned without displaying anything.

**Comment by seeker89** [comment]
Definitely. I think that an easy way to fix that would be to have a warning, when `find` results in an empty list.

**Comment by seeker89** [comment]
I guess we should address this issue before we celebrate its third anniversary :)
