### ISSUE TITLE
Participate in EuroPython 2020 Sprints

### ISSUE THREAD

**Issue by dgzlopes** [bloomberg/powerfulseal#246]
This year EuroPython sprints are free of charge and online! The organization will provide virtual rooms and guidance on how to run the sprints.

When? During the weekend: Saturday & Sunday July 25 & 26.

I think this is a great opportunity for:
- Promoting Powerfulseal
- Helping newcomers
     *  People who want to learn more about the project and how to use it.
     *  People who want to start contributing to Powerfulseal.
- Making the Seal more powerful
     * 3.0.0 :eyes: 
     * For example, we can finally work on #202 (or in an alternative to it)
- Making the Seal easier to understand (docs, docs, docs!)

More info about the sprints [here](https://ep2020.europython.eu/events/sprints/). More info about EuroPython [here](https://ep2020.europython.eu/).

I know there is still a long way to go until the event... but it is better to discuss it in advance :)

**Comment by seeker89** [comment]
This sounds like a really cool idea!

**Comment by dgzlopes** [comment]
Glad you like the idea :)

If you don't have plans for those days... I think we should participate! 

I can add us to the Python.org wiki [[0](https://wiki.python.org/moin/EuroPython2020/Sprints)], so people can register in our Sprint. 

We have time until early July to `concrete` the work for those days but in the meantime, I can put together a small info page (Inspiration: Python Packaging [[1](https://wiki.python.org/moin/EuroPython2020/PackagingSprint)]).

**Comment by seeker89** [comment]
Damn, this slipped through the cracks. Sorry...

**Comment by dgzlopes** [comment]
np @seeker89 we can always participate next year :) 

On the other hand, If you're ok, maybe we can tag some issues for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - I'm sure it drives some new people to the project.

**Comment by seeker89** [comment]
This sounds like a great idea. Do you know what needs to be done on our side?

**Comment by dgzlopes** [comment]
I think we've good "Contribute to Powerfulseal" docs, but maybe we can give them a second look. We've to pick well-defined and self-contained issues and apply the `Hacktobertest` label.
