### ISSUE TITLE
The docker image(3.0.0rc8)  does not exist.

### ISSUE THREAD

**Issue by monadbobo** [bloomberg/powerfulseal#279]
The docker image does not exist.

I failed to execute kubectl create -f powerfulseal.yaml, logging Showing:

"Error from server (BadRequest): container "powerfulseal" in pod "powerfulseal-94749589f-vxstx" is waiting to start: trying and failing to pull image"

**Comment by seeker89** [comment]
Good catch, let me see what happened.

**Comment by seeker89** [comment]
The image seems to exist: https://hub.docker.com/layers/bloomberg/powerfulseal/3.0.0rc8/images/sha256-7bd88efc45b9e244bdccba5bd564d8b69e5f76993cc14fb5ad63c0a5b9870d94?context=explore 

Closing. Feel free to re-open if still needed.
