### ISSUE TITLE
 Add aarch64 support to powerfulseal

### ISSUE THREAD

**Issue by odidev** [bloomberg/powerfulseal#288]
Hi Team,

It will be very helpful if we have aarch64 support added in docker containers.

Currently, this project focuses on making amd64 docker containers. For including aarch64 support, I have just added libssl-dev, libffi-dev dependencies and used kubectl-aarch64 in the RUN clause of Dockerfile. This has successfully generated an aarch64 docker image. If this sounds feasible, I would like to raise a PR for including aarch64 support to powerfulseal, and add arm64 jobs in .travis.yml as well.

Dockerfile: https://github.com/odidev/powerfulseal/blob/master/build/Dockerfile
Travis report: https://travis-ci.com/github/odidev/powerfulseal

Please share your opinion on the same.

**Comment by seeker89** [comment]
Hi @odidev and thanks for the issue!

I don't see why not. The only downside seems to be that the arm jobs seem to be taking 25 minutes to build!

You're most welcome to send the PR. Do we need to change the base image for the arm64 builds?

Also, I'd be super interested to know what your use case is (if you can disclose) - as far as I know that'll be the first time the Seal is run on arm 👍

**Comment by odidev** [comment]
Hi seeker89
Thanks for the reply. It is helpful for projects using this project as a dependency in a multiarch environment. I have raised the PR with aarch64 support.
