### ISSUE TITLE
Wrong import breaking cli

### ISSUE THREAD

**Issue by taliaga** [bloomberg/powerfulseal#36]
Hi!

I wanted to try powerfulseal, but I found that after pipi-installing it I cannot even run the help command. It seems there's a dependency issue in the python package (you may want to check the ci job of master, it should be failing).

I noticed `os_client_config` is now embedded into `openstack` package, so a simple patch like the following would do.

```

diff --git a/powerfulseal/clouddrivers/open_stack_driver.py b/powerfulseal/clouddrivers/open_stack_driver.py
index 71708a1..c343f08 100644
--- a/powerfulseal/clouddrivers/open_stack_driver.py
+++ b/powerfulseal/clouddrivers/open_stack_driver.py
@@ -15,15 +15,14 @@


 import logging
-import os_client_config
-from openstack import connection
 from . import AbstractDriver
 from ..node import Node, NodeState


 def create_connection_from_config(name=None):
     """ Creates a new open stack connection """
-    occ = os_client_config.OpenStackConfig()
+    from openstack import connection, OpenStackConfig
+    occ = OpenStackConfig()
     cloud = occ.get_one_cloud(name)
     return connection.from_config(cloud_config=cloud)

@@ -106,4 +105,3 @@ class OpenStackDriver(AbstractDriver):
         """ Delete a Node permanently.
         """
         self.conn.compute.delete_server(node.id)
-

```

**Comment by seeker89** [comment]
Hi @taliaga thanks for filing this in. We just discovered this in https://github.com/bloomberg/powerfulseal/pull/35#pullrequestreview-92065789 - they changed the API in the minor release, so we need to update the Seal to reflect that.

I'll do that ASAP.
