### ISSUE TITLE
Additional steps for Oracle Linux 7.3, Python 2.7.5 for installing dependencies and compilation issues

### ISSUE THREAD

**Issue by pawarmanoj** [bloomberg/powerfulseal#50]
On my Oracle Linux 7.3 box with Python 2.7.5, I had to perform some additional steps to get powerfulseal to work. 
$ **`sudo pip install powerfulseal`**
`Installing collected packages: ConfigArgParse, click, MarkupSafe, Jinja2, Werkzeug, itsdangerous, Flask, termcolor, pyparsing, packaging, deprecation, iso8601, pbr, stevedore, keystoneauth1, os-service-types, munch, netifaces, futures, appdirs, requestsexceptions, jmespath, jsonpointer, jsonpatch, dogpile.cache, openstacksdk, bcrypt, asn1crypto, cryptography, pynacl, paramiko, spur, python-dateutil, pyasn1-modules, rsa, httplib2, oauth2client, kubernetes, powerfulseal
`
  `Running setup.py install for ConfigArgParse ... done`
  `Running setup.py install for MarkupSafe ... done`
  `Running setup.py install for itsdangerous ... done`
  `Running setup.py install for termcolor ... done`
  `Found existing installation: pyparsing 1.5.6
    DEPRECATION: Uninstalling a distutils installed project (pyparsing) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.`
    `Uninstalling pyparsing-1.5.6:
     Successfully uninstalled pyparsing-1.5.6`
  `Running setup.py install for deprecation ... done`
  `Running setup.py install for munch ... done`
  `Running setup.py install for netifaces ... done`
  `Running setup.py install for dogpile.cache ... done`
  `Found existing installation: cryptography 1.3.1
    Uninstalling cryptography-1.3.1:
      Successfully uninstalled cryptography-1.3.1`
  `Running setup.py install for httplib2 ... done`
  `Running setup.py install for powerfulseal ... done`
`Successfully installed ConfigArgParse-0.13.0 Flask-0.12.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 appdirs-1.4.3 asn1crypto-0.24.0 bcrypt-3.1.4 click-6.7 cryptography-2.2.2 deprecation-2.0.2 dogpile.cache-0.6.5 futures-3.2.0 httplib2-0.11.3 iso8601-0.1.12 itsdangerous-0.24 jmespath-0.9.3 jsonpatch-1.23 jsonpointer-2.0 keystoneauth1-3.5.0 kubernetes-1.0.2 munch-2.3.1 netifaces-0.10.6 oauth2client-4.1.2 openstacksdk-0.12.0 os-service-types-1.2.0 packaging-17.1 paramiko-2.4.1 pbr-4.0.2 powerfulseal-1.1.1 pyasn1-modules-0.2.1 pynacl-1.2.1 pyparsing-2.2.0 python-dateutil-2.7.2 requestsexceptions-1.4.0 rsa-3.4.2 spur-0.3.20 stevedore-1.28.0 termcolor-1.1.0
`

after I completed the installation for powerfulseal (as per logs above), I wasn't able to execute powerfulseal. 
In order to resolve the issues, these are the steps that I had to perform - 
 
1. **`sudo pip install pyasn1 --upgrade`**
2. **`sudo pip install cffi --upgrade`**
3. **`sudo pip install configparser`**

4. File:  "/usr/lib/python2.7/site-packages/powerfulseal/cli/pscmd.py" - Added the line below to the top of the file.
`from __future__ import print_function`

5. File: /usr/lib/python2.7/site-packages/powerfulseal/clouddrivers/driver.py - Added the first two lines to import six for compatibility and updated the code as shown in line 3 below.
`import abc, six`
`@six.add_metaclass(abc.ABCMeta)`
`class AbstractDriver():`

**Comment by seeker89** [comment]
Hi @pawarmanoj, thanks for the issue.

We were only targeting python 3.4+, but from a quick read I think it would be fairly straightforward to add support for py27.

Do you have a use case that requires you to run it on python 2.7 ?

**Comment by seeker89** [comment]
Python 2.7 support has been added via https://github.com/bloomberg/powerfulseal/pull/59
