### ISSUE TITLE
Add python 2.7 support

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#51]
A lot of people approached me to ask about the python 2.7 support.

If you need it for your setup, please vote for this issue.

**Comment by maheshkolli** [comment]
Yes please provide python 2.7 support.
 We have been trying to use powerfulseal from around 6 weeks but unfortunately it is using python 2.7 and  powerfu seal packages are being installed in python 2.7  . Tried several ways to make python3 as default but nothing working.

**Comment by pawarmanoj** [comment]
Even I am facing the same issue. Even though I have made python 3.6 and pip 10.1 as the default options, and installed powerfulseal after ensuring that python3.6 is the default python version, yet seal executes with python 2.7

**Comment by kz** [comment]
@pawarmanoj If you are working with multiple Python versions, I would recommend using `pyenv` or virtual environments.
