### ISSUE TITLE
policy file configuration

### ISSUE THREAD

**Issue by snehalbiche** [bloomberg/powerfulseal#68]
Hi, 
need more explanation on how this works in total?
my expectation was after setting below in policy file powerfulseal will start killing my pods once the start time hits and will run for 24 hours. but that never the case it start with saying too early and then continuously shows too late, why?

current time was :-  12: 01
The day of week :- Monday

My current configuration in policy file as below -
      - dayTime:
          onlyDays:
            - "monday"
            - "tuesday"
#            - "wednesday"
#            - "thursday"
#            - "friday"
#            - "saturday"
#            - "sunday"
         startTime:
            hour: 12
            minute: 03
            second: 00
          endTime:
            hour: 11
            minute: 50
            second: 00

From logs - 

INFO:powerfulseal.cli.__main__:Attempting to read the inventory from kubernetes
ERROR:powerfulseal.clouddrivers.no_cloud_driver:Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
INFO:powerfulseal.policy.scenario.The Chaos Testing:Matched 1 pods in namespace powerfulsealtest
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Matching [pod #0 name=sise-748bf8d98b-w29qk namespace=powerfulsealtest containers=1 ip= host_ip= state=Running labels:owner=luser,pod-template-hash=3046948546,run=sise]
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Initial set length: 1
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter property: 1 -> 1 items
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter property: 1 -> 1 items
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Now is datetime.datetime(2018, 9, 3, 12, 2, 9, 10619)
**### INFO:powerfulseal.policy.scenario.The  Chaos Testing:Too early**
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter dayTime: 1 -> 0 items
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Empty set after {'dayTime': {'onlyDays': ['monday', 'tuesday'], 'startTime': {'second': 0, 'hour': 12, 'minute': 3}, 'endTime': {'second': 0, 'hour': 11, 'minute': 50}}}
Filtered to empty set 
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filtered set length: 0
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Done
INFO:powerfulseal.policy.policy_runner:Sleeping for 177 seconds
ERROR:powerfulseal.clouddrivers.no_cloud_driver:Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Matched 1 pods in namespace powerfulsealtest
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Matching [pod #0 name=sise-748bf8d98b-w29qk namespace=powerfulsealtest containers=1 ip= host_ip= state=Running labels:owner=,pod-template-hash=3046948546,run=sise]
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Initial set length: 1
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter property: 1 -> 1 items
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter property: 1 -> 1 items
INFO:powerfulseal.policy.scenario.The Chaos Testing:Now is datetime.datetime(2018, 9, 3, 12, 3, 23, 774632)
### INFO:powerfulseal.policy.scenario.The  **Chaos Testing:Too late**
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filter dayTime: 1 -> 0 items
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Empty set after {'dayTime': {'onlyDays': ['monday', 'tuesday'], 'startTime': {'second': 0, 'hour': 12, 'minute': 3}, 'endTime': {'second': 0, 'hour': 11, 'minute': 50}}}
Filtered to empty set 
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Filtered set length: 0
INFO:powerfulseal.policy.scenario.The  Chaos Testing:Done
INFO:powerfulseal.policy.policy_runner:Sleeping for 301 seconds

**Comment by kz** [comment]
Hi, thanks for getting in touch. Have you tried changing your end time to be after your start time? That's a good edge case I should add validation for. Note that 11pm => 23

**Comment by snehalbiche** [comment]
@kz Thanks for information let me try but I need to run the powerfulseal for next 24 hours ir-respective of when it starts.
So If i start at Monday 12:00:00 then my 24 hours ends on Tuesday. 
If I run from 12PM to 23PM then it is just 11 hours of run, not 24 hours.
