### ISSUE TITLE
Will Powerful seal works for Openshift Origin ?

### ISSUE THREAD

**Issue by kthallam** [bloomberg/powerfulseal#69]
Hi Team, 

Will Powerful seal works for the open shift origin ? 

Thanks

**Comment by forexpiphunter** [comment]
Hi,
Can we get an update on this from the team?  I'm also interested in knowing if this will work with Openshift Origin...

Thanks!

**Comment by seeker89** [comment]
Hi @kthallam, @forexpiphunter - while we haven't testing it with openshift, I don't see why it wouldn't.

As long as your `kubectl` can use the `kubeconfig`, the seal should be able to use it too.

Let me know if you run into any issues - happy to help. Will close in the meantime 👍
