### ISSUE TITLE
Use baremetal Kubernetes cluster?

### ISSUE THREAD

**Issue by dkirrane** [bloomberg/powerfulseal#70]
Can I point seal at a standard KUBE_CONFIG to access a baremetal cluster and kill pods?

**Comment by seeker89** [comment]
Hi @dkirrane yup, that's the idea with `--no-cloud` flag. Have you given this a try ?

**Comment by seeker89** [comment]
Hi @dkirrane - have you given it a try ? Can we close the issue ?
