### ISSUE TITLE
Docker command

### ISSUE THREAD

**Issue by forexpiphunter** [bloomberg/powerfulseal#73]
any reason why I'm getting state=NodeState.UNKNOWN
(seal) $ sync
ERROR:powerfulseal.clouddrivers.no_cloud_driver:Trying to sync things while using a no-cloud driver. If you don't expect to be seeing this, you might want to rethink some of your choices
[node no=30 id=fake-172.17.1.171 ip=172.17.1.171 az=nope groups=['amd64', 'kube-master-1.onprem.domain.com', 'linux', 'true'] name=local-172.17.1.171 state=NodeState.UNKNOWN]

**Comment by seeker89** [comment]
From your logs, it looks like this is because you are running with `--no-cloud` option. In this state, it will not be able to read the cloud api and fetch the status of the machine.

**Comment by seeker89** [comment]
Closing this issue, feel free to reopen if you'd like to know more.
