### ISSUE TITLE
Can't figure out how to provide an inventory for autonomous mode

### ISSUE THREAD

**Issue by pycaster** [bloomberg/powerfulseal#76]
Hi,

Can you please provide me an example of an inventory file (apart from the one in tests) that allows me to match with group properties in the node_scenarios policy. I use this now,

```
[c]
52.58.80.238

[a]
3.120.248.11

[workers:children]
c
a
```

How do I provide more info here to match to the group properties for a policy like below?

```
config:
  minSecondsBetweenRuns: 3600
  maxSecondsBetweenRuns: 7200

# the scenarios describing actions on nodes
nodeScenarios:

# example of a policy using al the filters available
- name: "reboot control node"

  # Choose the initial set of nodes to operate on.
  # Note that this will be an union of all the notes you match (logical OR)
  match:
  - property:
      name: "group"
      value: "a"

  # The filters are executed in the order specified and can be
  # used multiple times, and piped from one to the next.
  filters:

  # property filters (all the property filters support regexp)
  - property:
      name: "group"
      value: "a"

  # time of execution filters
  # to restrict the actions to work days, you can do
  - dayTime:
      onlyDays:
      - "monday"
      - "tuesday"
      - "wednesday"
      - "thursday"
      - "friday"
      startTime:
        hour: 18
        minute: 30
        second: 0
      endTime:
        hour: 22
        minute: 30
        second: 0

  # to pick a random sample of nodes/pods, you can specify either a size
  - randomSample:
      size: 1

  # this will pass all the nodes with the given probability,
  # or none otherwise
  - probability:
      probabilityPassAll: 1

  # The actions will be executed in the order specified
  actions:
  - stop:
      force: false
  - wait:
      seconds: 600
  - start:
  - wait:
      seconds: 1000
  - execute:
      cmd: "hostname"
```

I would like to use ip, az and name group properties.

**Comment by seeker89** [comment]
Hey, thanks for the question.

With the example that you provided (I assume that you are running it with `--no-cloud` ?) you should be able to match on the group names. Please check [our test that covers that](https://github.com/bloomberg/powerfulseal/blob/master/tests/node/test_inventory.py#L23-L28), and if you think that it's an issue, please feel free to add a failing test and we'll be happy to fix it.

Now that I'm reading through the tests, I do see though, that there is no test for checking that these groups are included when executing the matchers, so we might need to look into it.

With things like availability zones, on the other hand, there is no way to do that with just an inventory file - you will need to use a cloud driver to read that - in which case, the inventory basically become a filter of which nodes will ever be touched.

**Comment by seeker89** [comment]
Closing this now. Feel free to reopen if you have any more questions!
