### ISSUE TITLE
Can we run Powerfulseal in GCP/GKE?

### ISSUE THREAD

**Issue by narendra15** [bloomberg/powerfulseal#80]
Hello Team,

I have a project in GCP and have Kubernetes cluster in it where in for my testing purpose I am planning to kill my pods/nodes using Powerfulseal. Can you please let me know if Powerfulseal supports with  GCP/GKE.

**Comment by seeker89** [comment]
Hey,

I haven't tested it with the GKE hosted kubernetes, so there might be some adjustments to make to make it work. 

I'm happy to help with that. We can use this issue to track any issues and changes needed for GKE.

If by GCP you mean a self-deployed Kubernetes cluster on Google cloud, then the setup shouldn't be any different from the usual.

Either way - it should be easy to do, put any issues here, and we'll try to resolve.

**Comment by narendra15** [comment]
Thanks a lot for the reply and quick update, it would be great if the Powerfulseal works for my project.
 I have followed the below steps to run Powerfulseal to run against by GCP Kubernetes Cluster.
1. Has powerfulseal installed in my system.
2. Have a Kube config configured.
3. When trying to run the below command:
python -m powerfulseal.cli --kube-config \.kube\config --label --inventory-kubernetes
It gives below error that an argument is required for cloud. Can you please let me know what should I give for GKE/ GCP environment kubernetes. Also can you please let me know how to configure the cloud_config file and where in the command I should be using.
usage: __main__.py [-h] [-c CONFIG] [-v]
                   (--validate-policy-file VALIDATE_POLICY_FILE | --run-policy-file RUN_POLICY_FILE | --interactive | --label | --demo)
                   [--heapster-path HEAPSTER_PATH]
                   [--aggressiveness AGGRESSIVENESS] [--namespace NAMESPACE]
                   [--min-seconds-between-runs MIN_SECONDS_BETWEEN_RUNS]
                   [--max-seconds-between-runs MAX_SECONDS_BETWEEN_RUNS]
                   [--server] [--server-host SERVER_HOST]
                   [--server-port SERVER_PORT]
                   (-i INVENTORY_FILE | --inventory-kubernetes)
                   [--remote-user REMOTE_USER] [--ssh-allow-missing-host-keys]
                   [--ssh-path-to-private-key SSH_PATH_TO_PRIVATE_KEY]
                   (--open-stack-cloud | --aws-cloud | --no-cloud)
                   [--open-stack-cloud-name OPEN_STACK_CLOUD_NAME]
                   [--stdout-collector | --prometheus-collector]
                   [--prometheus-host PROMETHEUS_HOST]
                   [--prometheus-port PROMETHEUS_PORT]
                   [--kube-config KUBE_CONFIG]
__main__.py: error: one of the arguments --open-stack-cloud --aws-cloud --no-cloud is required

**Comment by sb185234** [comment]
Hi Mikolaj,

Can you please let us know the changes for running powerfulseal against the GKE cluster.

Thank you
Sireesha

**Comment by seeker89** [comment]
I suggest we start by making the kubernetes part working - so try to run with `--no-cloud` flag first.

Looking at https://cloud.google.com/kubernetes-engine/docs/quickstart, it appears that the install command for local shell should give you a functional local `kubectl`:

```sh
gcloud components install kubectl
```

So at that point, you should be able to point the Seal at the same kubeconfig file that it uses and be good to go. Please check that and tell me if there are any problems.

**Comment by seeker89** [comment]
@narendra15 @sb185234 I have just merged in a refactor of the command line flags, which will be released as version 2.0.0 very soon.

If you'd like to use it, please just check out the code from the master branch.

It has some changes that are useful for minikube: https://github.com/bloomberg/powerfulseal#minikube-setup which might be useful in your case.

**Comment by seeker89** [comment]
Hey, following up @narendra15 @sb185234 - how are you doing with this ?

**Comment by seeker89** [comment]
GCP driver has now been merged in. Closing !
