### ISSUE TITLE
Can I use powerfulseal in a private cloud?

### ISSUE THREAD

**Issue by zhanghuidinah** [bloomberg/powerfulseal#88]
Whether to support？

**Comment by zhanghuidinah** [comment]
- When trying to run the below command:

```
python -m powerfulseal.cli --kube-config ./129.20.kubeconfig --inventory-kubernetes --interactive -v
```

- It gives below error
```
usage: __main__.py [-h] [-c CONFIG] [-v]
                   {interactive,autonomous,label,demo,validate} ...
__main__.py: error: argument mode: invalid choice: './129.20.kubeconfig' (choose from 'interactive', 'autonomous', 'label', 'demo', 'validate')
```

**Comment by zhanghuidinah** [comment]
- And I switch  autonomous mode to test  run the below command:

```
seal -vv autonomous --no-cloud --policy-file ./examples/policy_kill_random_default.yml --inventory-kubernetes --remote-user docker --ssh-path-to-private-key caicloud2018-qa2 --override-ssh-host 192.168.131.1 --host 192.168.129.20 --port 6060
```

- It gives below error

```
Error return code: {'ret_code': 1, 'error': "Error creating SSH connection\nOriginal error: Server '192.168.131.1' not found in known_hosts"}
```

**Comment by seeker89** [comment]
> * And I switch  autonomous mode to test  run the below command:
> 
> ```
> seal -vv autonomous --no-cloud --policy-file ./examples/policy_kill_random_default.yml --inventory-kubernetes --remote-user docker --ssh-path-to-private-key caicloud2018-qa2 --override-ssh-host 192.168.131.1 --host 192.168.129.20 --port 6060
> ```
> * It gives below error
> 
> ```
> Error return code: {'ret_code': 1, 'error': "Error creating SSH connection\nOriginal error: Server '192.168.131.1' not found in known_hosts"}
> ```

Hi, this error says that the hosts you are trying to reach are not in your `known_hosts`. You can either put them there, or use `--ssh-allow-missing-host-keys` flag to ignore that.

**Comment by zhanghuidinah** [comment]
- Now encountered the problem: direct ssh can log in, but also meet some error  when I run seal：

```
seal -v autonomous --no-cloud --policy-file ./examples/policy_kill_random_default.yml --inventory-kubernetes --ssh-allow-missing-host-keys --remote-user root --ssh-path-to-private-key ~/.ssh/key --host 0.0.0.0 --port 8091 --kubeconfig powerfulseal.kubeconfig
``` 
- It gives below error

```
'ret_code': 1, 'error': 'Error creating SSH connection\nOriginal error: Authentication failed.'
```

**Comment by zhanghuidinah** [comment]
ref：https://github.com/bloomberg/powerfulseal/pull/89
