### ISSUE TITLE
Expose a maximum number of loops for autonomous mode

### ISSUE THREAD

**Issue by jeffb4** [bloomberg/powerfulseal#90]
The `PolicyRunner.run` method supports a maximum number of times to run (`loops=` named parameter) but this is not exposed as far as I can see in a useful manner.

A CLI flag of the maximum number of loops would be useful for testers/scripters who'd like to run PS scenarios a set number of times and then exit, to present test run results.

(I have this exposure implemented privately, and am willing to contribute it, but wanted to get the idea vetted first)

**Comment by seeker89** [comment]
Hey @jeffb4 that sounds like a quick win. Definitely worth contributing 👍

**Comment by seeker89** [comment]
And sorry for taking so long to get back to you - the holiday season !

**Comment by seeker89** [comment]
Hey @jeffb4 following up on this - are you still keen on contributing this ?

**Comment by jeffb4** [comment]
I am, do you have any implementation preferences? I can submit a PR with what I've done and you can check it out, but if you've got definite opinions might be best to skip straight to those.

**Comment by seeker89** [comment]
We've gotten multiple requests for that recently, so this goes up the stack !
