### ISSUE TITLE
Filter based on allowed match mappings

### ISSUE THREAD

**Issue by jeffb4** [bloomberg/powerfulseal#91]
Scenario: multiple pod-specific matchers are used to match pods (namespace and deployment) and I wish to use a filter of the same criteria to effectively make the match an AND operation instead of OR

Currently there is no way to filter on these pod-specific matchers, being instead limited to property/dayTime/randomSample/probability (populated in the filter mapping in `scenario.py`)

I'd like to propose adding the capability for pod_scenario and node_scenario to optionally add to the filter mapping to provide their own filters for cases that make sense.

**Comment by seeker89** [comment]
I guess currently you could work around that by creating multiple scenarios, one for the namespace, another one for the deployment. Is that something that you need to solve your use case, or more of a nice-to-have ?

**Comment by seeker89** [comment]
It went silent for over a year, I'll close it, feel free to reopen if still needed.

**Comment by jeffb4** [comment]
Sorry for letting this languish unanswered, Mikolaj. I changed employers a year ago and stopped using powerfulseal and absolutely forgot I'd opened an issue.

Thanks for all the work you do on the project, it was very useful for what I needed.
