### ISSUE TITLE
Negative match and filter logic

### ISSUE THREAD

**Issue by jeffb4** [bloomberg/powerfulseal#92]
Scenario: powerfulseal is hosted in a cluster it is chaosing. It would be useful to be able negative match and filter logic - that is the ability to say "match nodes that are NOT ip-foo-bar" and "filter for nodes that are NOT ip-foo-bar" to allow powerfulseal to do safer node kills in this situation

Because property_match uses a regex SOME of this functionality could, with some work, be done. The addition of a property_not mapping, however, would provide easier negation logic for policy writers

**Comment by seeker89** [comment]
Hey @jeffb4 thanks for the suggestion. I definitely see how that could be useful, even just to explicitly ban some nodes for the peace of mind.
