### ISSUE TITLE
AWS Driver Does Not Return Public IP of Node

### ISSUE THREAD

**Issue by mikeln** [bloomberg/powerfulseal#99]
Given:
 running kubernetes on aws
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Powerfulseal version.  (no version command...that should be added...)

Running powerfulseal external to the target kubernetes cluster

Issues:
Unable to get an accessible IP for each Node to perform the desired actions.

Analysis:
The node object does not have a field to capture a public IP (or external IP).  It only contains the internal cluster IP.   
The AWS cloud driver does get the public_ip, but the implementation does not return that IP when matching a pod's IP address (which is usually the internal IP address).
The nodes internal IP address is not accessible from outside the kubernetes cluster.

Proposed Solution:
1) add and external IP field to the node object
2) update the cloud drivers to populate that field correctly (if available)
3) update cloud drivers (AWS in particular) to return the matching node (including the external IP field)
4) update node_inventory to also find nodes based on external IP
5) update tests to test this added node field.

I have a working version and will PR it back, if you find the proposal acceptable.

**Comment by seeker89** [comment]
I agree with both the analysis and the proposed solution.

It sounds like a great ratio effort to more use cases covered.

Excellent suggestion, thanks @mikeln !

**Comment by mikeln** [comment]
ok, I'll have a PR ready probably by tomorrow.  Still testing.

**Comment by mikeln** [comment]
https://github.com/bloomberg/powerfulseal/pull/107
